repos:
- repo: git@github.com:awslabs/git-secrets.git
  rev: master # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    -  id: git-secrets
      name: Git Secrets

  - repo: git@github.com:antonbabenko/pre-commit-terraform.git
    rev: master 
    hooks:
      - id: terraform_tflint
        name: Terraform validate with tflint