name: migrationDeployment
on:
  push:
    branches:
      main

jobs:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    pull-requests: write
  steps:
    - name: terraform initilization
      run: terraform init   

    - name: terraform planning
      run: terraform plan

    - name: terraform applying
      run: terraform apply -auto-approve       
      
    - name: terraform validating
      run: terraform validate

    - name: terraform format
      run: terraform fmt
