name: migrationDeployment
on:
  push:
    branches:
      main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Clone our repository
        uses: actions/checkout@v3

      - name: AWS Authentication
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::637448446398:oidc-provider/token.actions.githubusercontent.com
          aws-region: eu-central-1
          role-session-name: Githubmigrationdeploy
      - name: terraform initilization
        run: terraform init   

      - name: terraform planning
        run: terraform plan

      - name: terraform applying
        run: terraform apply -auto-approve       
      
      - name: terraform validating
        run: terraform validate

      - name: terraform format
        run: terraform fmt
